stages:
  - build

build-apk:
  stage: build
  image: cirrusci/flutter
  script:
    - flutter build apk
    - mv build/app/outputs/apk/release/app-release.apk photoprism.apk
  artifacts:
    paths:
      - photoprism.apk
