stages:
  - build
  - deploy

build-apk:
  stage: build
  image: cirrusci/flutter
  script:
    - flutter build apk
    - mv build/app/outputs/apk/release/app-release.apk photoprism.apk
  artifacts:
    paths:
      - photoprism.apk

pages:
  stage: deploy
  dependencies:
  - build-apk
  script:
  - mkdir public
  - cp photoprism.apk public/
  artifacts:
    paths:
    - public
  only:
  - master

